name: Test

on: push

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        os: [ ubuntu-latest ]
        python-version: [ '3.7' ]
    name: Python ${{ matrix.python-version }} ${{ matrix.os }}

    steps:
    - uses: actions/checkout@v2

    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}

    - name: Install
      run: |-
        python --version
        python -m pip install --upgrade pip
        pip install -r requirements.txt pytest

        PYTHONPATH=. pytest tests

    - name: Test canary
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |-
        DUMMY_ANNOTATION=true python main.py tests/canary.py LICENSE
